version: "3.3"
services: 
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports: 
      - "2181:2181"
       
    environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
       container_name: zookeeper
    networks:
      vpcbr:
        ipv4_address: 192.168.99.105
  kafka:
    image: confluentinc/cp-kafka  
    environment: 
      ADVERTISED_HOST: "192.168.99.100"
      ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:10091
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    ports: 
      - "9092:9092"
    networks:
      vpcbr:
        ipv4_address: 192.168.99.106
  db:
    image: cassandra
    hostname: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 192.168.99.100
    ports:
       - "7191:7191"  
       - "7000:7000" 
       - "7001:7001" 
       - "9160:9160" 
       - "9042:9042" 
    volumes:
        - D:/Docker/Cassandra_DB/data/:/var/lib/cassandra
    #networks:
    #  vpcbr:
    #    ipv4_address: 192.168.99.107
  tomcat1:
    image: test/tomcat1
    hostname: tomcat1
    ports:
        - "7070:8080"
  tomcat2:
     image: test/tomcat2
     hostname: tomcat2
     ports:
        - "9090:8080"
  vjapache2:
    #https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html
    image: test/vjapache2
    hostname: vjapache
    ports:
        - "8080:8080"
        - "80:80"

  uapache:
    image: test/uapache
    hostname: apache
    ports:
        - "80:80"
        
  
  vjapache:
    image: test/vjapache
    hostname: vjapache
    ports:
        - "8080:8080"
        - "80:80"
    depends_on:
        - tomcat1
  web:
    image: tomcat:8.0
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    networks:
      vpcbr:
        ipv4_address: 192.168.99.108

networks:
  vpcbr:
    driver: bridge
    ipam:
        config:
          - subnet: 192.168.99.100/16
          
            